version: '3'
services:
  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
    networks:
      - selenium_grid

  selenium-hub:
    image: selenium/hub:latest
    ports:
      - "4444:4444"
    networks:
      - selenium_grid

  chrome:
    image: selenium/node-chrome:latest
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
    networks:
      - selenium_grid

  edge:
    image: selenium/node-edge:latest
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
    networks:
      - selenium_grid

networks:
  selenium_grid:
    driver: bridge

volumes:
  jenkins_home:
